# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = "  "

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[buf]
symbol = " "

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✗](bold red)"

[cmake]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'
min_time = 10_00

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'
symbol = " "

[crystal]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[deno]
format = '\[[$symbol($version)]($style)\]'

[directory]
disabled = false
fish_style_pwd_dir_length = 0
format = '[$path]($style) [$read_only]($read_only_style)'
home_symbol = '~'
read_only = " 󰌾"
read_only_style = 'red'
style = 'fg:85 bold'
truncation_length = 5
truncation_symbol = '.../'
truncate_to_repo = false
use_logical_path = false

[docker_context]
format = '\[[$symbol$context]($style)\]'
symbol = " "

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[elm]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_commit]
commit_hash_length = 7
tag_symbol = '  '

[git_state]
am = 'AM'
am_or_rebase = 'AM/REBASE'
bisect = 'BISECTING'
cherry_pick = 'CHERRY-PICK'
disabled = false
format = '\([$state( $progress_current/$progress_total)]($style)\)'
merge = 'MERGING'
rebase = 'REBASING'
revert = 'REVERTING'
style = 'bold yellow'

[git_status]
ahead = "↑${count} "
behind = "↓${count} "
conflicted = "≠${count} "
diverged = "↕${ahead_count} ${behind_count}"
format = """\\[\
[$ahead_behind](bold green)\
[$stashed](bold green)\
[$behind_behind](bold red)\
[$diverged](bold yellow)\
[$conflicted](bold red)\
[$modified](bold blue)\
[$untracked](bold cyan)\
[$staged](bold green)\
\\]
"""
modified = "!${count}"
staged = "✓${count}"
stashed = "*${count}"
style = "bright-white"
untracked = "?${count}"

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[gradle]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[guix_shell]
format = '\[[$symbol]($style)\]'
symbol = " "

[haskell]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[haxe]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[hostname]
disabled = false
format = '[$hostname]($style) '
ssh_only = false
ssh_symbol = " "
trim_at = "."

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[julia]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kotlin]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'
symbol = '☸ '

[lua]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "󰍛 "

[meson]
format = '\[[$symbol$project]($style)\]'
symbol = "󰔷 "

[nim]
format = '\[[$symbol($version)]($style)\]'
symbol = "󰆥 "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
symbol = " "

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
disabled = false
format = '[$symbol]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
format = '\[[$symbol$version]($style)\]'
symbol = "󰏗 "

[perl]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[php]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'
symbol = " "

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[rlang]
symbol = "󰟔 "

[ruby]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "󱘗 "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[shell]
disabled = false
bash_indicator = "bash"
powershell_indicator = "ps"
cmd_indicator = "cmd"
zsh_indicator = "zsh"

[solidity]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[username]
disabled = false
format = '[$user]($style)@'
show_always = true

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
symbol = " "
